language: python
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      python: "2.7"
    - os: linux
      dist: trusty
      python: "3.4"

install:
  - pip install numpy
  - if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl;
    fi
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.4" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then
      pip3 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp34-none-linux_x86_64.whl;
    fi

script: python -m unittest tests
